/**
 * src/github.ts
 * ---------------------------------------------------------------------------
 * The small amount of GitHub knowledge the agent needs to open a pull request.
 *
 * Parsing the remote is its own function because it is the part that silently
 * produces a wrong answer rather than an error: an SSH remote and an HTTPS
 * remote describe the same repository in different shapes, and getting it wrong
 * builds a plausible URL that points nowhere.
 * ---------------------------------------------------------------------------
 */

export interface Repo {
  owner: string;
  name: string;
}

/**
 * Read `owner/name` out of any form of GitHub remote.
 *
 * Handles `git@github.com:owner/name.git`, `https://github.com/owner/name.git`,
 * `ssh://git@github.com/owner/name` and the same without the `.git` suffix.
 * Returns null for anything that is not GitHub, so the caller can say so
 * instead of guessing.
 */
export function parseGitHubRemote(url: string): Repo | null {
  const trimmed = url.trim().replace(/\.git$/, '');

  const match =
    /^git@github\.com:(?<owner>[^/]+)\/(?<name>[^/]+)$/.exec(trimmed) ??
    /^ssh:\/\/git@github\.com\/(?<owner>[^/]+)\/(?<name>[^/]+)$/.exec(trimmed) ??
    /^https?:\/\/(?:[^@]+@)?github\.com\/(?<owner>[^/]+)\/(?<name>[^/]+)$/.exec(trimmed);

  const owner = match?.groups?.owner;
  const name = match?.groups?.name;
  return owner && name ? { owner, name } : null;
}

/** Branch name for one ticket. Deterministic, so a rerun reuses the branch. */
export function branchFor(ticket: string): string {
  return `agent/${ticket.toLowerCase()}`;
}

/** The page GitHub shows for opening a pull request from a pushed branch. */
export function compareUrl(repo: Repo, branch: string): string {
  return `https://github.com/${repo.owner}/${repo.name}/compare/${branch}?expand=1`;
}

/**
 * Body of the pull request the agent opens.
 *
 * Written for the human who has to approve it: what the agent claims to have
 * done, and what a reviewer should check that the automation cannot check for
 * itself. The unchecked boxes are the point. This is the human-in-the-loop step
 * expressed as a process rather than as a prompt.
 */
export function pullRequestBody(ticket: string, jiraBaseUrl: string | undefined): string {
  const ticketLink = jiraBaseUrl
    ? `[${ticket}](${jiraBaseUrl.replace(/\/$/, '')}/browse/${ticket})`
    : ticket;

  return [
    `Generated by the agent for ${ticketLink}.`,
    '',
    'Automated checks that already passed locally:',
    '',
    '- the spec runs green',
    '- the generated-test quality gate accepts it',
    '- ESLint, Prettier and `tsc` are clean',
    '',
    'What a human still has to judge, because no linter can:',
    '',
    '- [ ] the test actually covers what the ticket asks for',
    '- [ ] it would fail if the feature broke, rather than passing for another reason',
    '- [ ] any new knowledge-base entry is true, not a guess that happened to work',
    '',
    'The agent cannot merge this. That is the point.',
  ].join('\n');
}
